jvm_highcore_task:
  container:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
    cpu: 4
    memory: 8G
  matrix:
    - name: JVM high-core-count 2.13
      script: sbt '++ 2.13' testsJVM/test
    - name: JVM high-core-count 3
      script: sbt '++ 3' testsJVM/test

jvm_arm_highcore_task:
  arm_container:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
    cpu: 4
    memory: 8G
  matrix:
    - name: JVM ARM high-core-count 2.13
      script: sbt '++ 2.13' testsJVM/test
    - name: JVM ARM high-core-count 3
      script: sbt '++ 3' testsJVM/test

jvm_macos_highcore_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  matrix:
    - name: JVM Apple Silicon high-core-count 2.13
      script:
        - brew install sbt
        - sbt '++ 2.13' testsJVM/test

native_arm_task:
  arm_container:
    dockerfile: .cirrus/Dockerfile
    cpu: 2
    memory: 8G
  matrix:
    - name: Native ARM 2.13
      script: sbt '++ 2.13' testsNative/test
    - name: Native ARM 3
      script: sbt '++ 3' testsNative/test

native_macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  matrix:
    - name: Native Apple Silicon 2.13
      script:
        - brew install sbt
        - sbt '++ 2.13' testsNative/test
    - name: Native Apple Silicon 3
      script:
        - brew install sbt
        - sbt '++ 3' testsNative/test
